name: Scrape Latest Papers

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      
      - name: Run scraping script
        run: python scrape_papers.py
      
      - name: Commit and Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add papers/
          git commit -m "Updated papers via scraping" || echo "No changes"
          git push
